[2024-07-16T08:34:52.513+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T08:34:52.530+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-16T08:34:52.562+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T08:34:52.570+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-16T08:34:52.603+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-16T08:34:52.604+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-16T08:34:52.604+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-16T08:34:52.604+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-16T08:34:52.604+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-16T08:34:52.605+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [queued]>
[2024-07-16T08:34:52.609+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-16T08:34:52.609+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-16T08:34:52.611+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-16T08:34:52.611+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-16T08:34:52.611+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-16T08:34:52.611+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [queued]>
[2024-07-16T08:34:52.611+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-16T08:34:52.622+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_from_mysql> on 2024-07-16 08:34:51.049999+00:00
[2024-07-16T08:34:52.628+0000] {standard_task_runner.py:60} INFO - Started process 463 to run task
[2024-07-16T08:34:52.630+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_mysql_to_***', 'extract_from_mysql', 'manual__2024-07-16T08:34:51.049999+00:00', '--job-id', '1241', '--raw', '--subdir', 'DAGS_FOLDER/ex.py', '--cfg-path', '/tmp/tmptaeucxi_']
[2024-07-16T08:34:52.631+0000] {standard_task_runner.py:88} INFO - Job 1241: Subtask extract_from_mysql
[2024-07-16T08:34:52.631+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x7e1805484ca0>]
[2024-07-16T08:34:52.661+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T08:34:52.665+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [running]> on host 6dec4fd91ad6
[2024-07-16T08:34:52.665+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 463)
[2024-07-16T08:34:52.665+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 463)
[2024-07-16T08:34:52.665+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-16T08:34:52.691+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T08:34:52.692+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-16T08:34:52.695+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-16T08:34:52.710+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-16T08:34:52.718+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_mysql_to_***' AIRFLOW_CTX_TASK_ID='extract_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T08:34:51.049999+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T08:34:51.049999+00:00'
[2024-07-16T08:34:52.719+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-16T08:34:52.719+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-16T08:34:52.732+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ex.py", line 26, in extract_from_mysql
    df = mysql_hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 226, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 187, in get_conn
    conn = self.connection or self.get_connection(getattr(self, self.conn_name_attr))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 514, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_conn` isn't defined
[2024-07-16T08:34:52.734+0000] {taskinstance.py:527} DEBUG - Task Duration set to 0.129409
[2024-07-16T08:34:52.735+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-16T08:34:52.735+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_mysql_to_***, task_id=extract_from_mysql, execution_date=20240716T083451, start_date=20240716T083452, end_date=20240716T083452
[2024-07-16T08:34:52.744+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-16T08:34:52.744+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1241 for task extract_from_mysql (The conn_id `mysql_conn` isn't defined; 463)
[2024-07-16T08:34:52.762+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-16T08:34:52.776+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun etl_mysql_to_airflow @ 2024-07-16 08:34:51.049999+00:00: manual__2024-07-16T08:34:51.049999+00:00, state:running, queued_at: 2024-07-16 08:34:51.059050+00:00. externally triggered: True>: 3 task(s)
[2024-07-16T08:34:52.776+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun etl_mysql_to_airflow @ 2024-07-16 08:34:51.049999+00:00: manual__2024-07-16T08:34:51.049999+00:00, state:running, queued_at: 2024-07-16 08:34:51.059050+00:00. externally triggered: True>: 3 task(s)
[2024-07-16T08:34:52.776+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [up_for_retry]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-16T08:34:52.777+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-16T08:34:52.777008+00:00 and task will be retried at 2024-07-16T08:39:52.734562+00:00.
[2024-07-16T08:34:52.777+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-16T08:34:52.777008+00:00 and task will be retried at 2024-07-16T08:39:52.734562+00:00.
[2024-07-16T08:34:52.777+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.extract_from_mysql manual__2024-07-16T08:34:51.049999+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-16T08:34:52.777+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.transform_data manual__2024-07-16T08:34:51.049999+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'extract_from_mysql'}
[2024-07-16T08:34:52.777+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: etl_mysql_to_airflow.transform_data manual__2024-07-16T08:34:51.049999+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'extract_from_mysql'}
[2024-07-16T08:34:52.777+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.transform_data manual__2024-07-16T08:34:51.049999+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-16T08:34:52.778+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.transform_data manual__2024-07-16T08:34:51.049999+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-16T08:34:52.778+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.load_data manual__2024-07-16T08:34:51.049999+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'transform_data'}
[2024-07-16T08:34:52.778+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: etl_mysql_to_airflow.load_data manual__2024-07-16T08:34:51.049999+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'transform_data'}
[2024-07-16T08:34:52.778+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.load_data manual__2024-07-16T08:34:51.049999+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-16T08:34:52.778+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: etl_mysql_to_airflow.load_data manual__2024-07-16T08:34:51.049999+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-16T08:34:52.783+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
