[2024-07-17T09:12:14.776+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:12:14.785+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T09:12:14.793+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:12:14.795+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T09:12:14.810+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:12:14.811+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T09:12:14.811+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T09:12:14.816+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:12:14.816+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [queued]>
[2024-07-17T09:12:14.816+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:12:14.819+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T09:12:14.822+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T09:12:14.823+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:12:14.824+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [queued]>
[2024-07-17T09:12:14.824+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-17T09:12:14.833+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_hive_table> on 2024-07-17 09:10:32.305646+00:00
[2024-07-17T09:12:14.838+0000] {standard_task_runner.py:60} INFO - Started process 471 to run task
[2024-07-17T09:12:14.841+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hive_etl', 'create_hive_table', 'manual__2024-07-17T09:10:32.305646+00:00', '--job-id', '1616', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmp9lbglssx']
[2024-07-17T09:12:14.842+0000] {standard_task_runner.py:88} INFO - Job 1616: Subtask create_hive_table
[2024-07-17T09:12:14.842+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x799cf7552f80>]
[2024-07-17T09:12:14.870+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:12:14.873+0000] {task_command.py:423} INFO - Running <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [running]> on host a88c97f6715f
[2024-07-17T09:12:14.874+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 471)
[2024-07-17T09:12:14.874+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 471)
[2024-07-17T09:12:14.874+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T09:12:14.902+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:12:14.905+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T09:12:14.908+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T09:12:14.933+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T09:12:14.946+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hive_etl' AIRFLOW_CTX_TASK_ID='create_hive_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T09:10:32.305646+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T09:10:32.305646+00:00'
[2024-07-17T09:12:14.946+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T09:12:14.947+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T09:12:15.019+0000] {hive.py:609} DEBUG - TOpenSessionResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None), serverProtocolVersion=5, sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=b'\xa0\xb0\xf2\x05s\xe4HN\xa4\xb0\xb2\xcc+G\xc3\x85', secret=b'\xbd\x99\xc1\r\xe9\xa2F\xcd\xa8\xa7h\xea\x14\xad\xc5e')), configuration={'hive.server2.thrift.resultset.default.fetch.size': '1000'})
[2024-07-17T09:12:15.019+0000] {hive.py:475} INFO - USE `default`
[2024-07-17T09:12:15.019+0000] {hive.py:479} DEBUG - TExecuteStatementReq(sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=b'\xa0\xb0\xf2\x05s\xe4HN\xa4\xb0\xb2\xcc+G\xc3\x85', secret=b'\xbd\x99\xc1\r\xe9\xa2F\xcd\xa8\xa7h\xea\x14\xad\xc5e')), statement='USE `default`', confOverlay=None, runAsync=False, queryTimeout=0)
[2024-07-17T09:12:15.058+0000] {hive.py:609} DEBUG - TExecuteStatementResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None), operationHandle=TOperationHandle(operationId=THandleIdentifier(guid=b'\xab2Z\xdb\xf7\nL]\xb0\xde3s\xe5&\x94\xad', secret=b'\xa6\xae\x15\x9cMbC\x10\xb5=\x7f\xcf\x0c\x80\xed\xb0'), operationType=0, hasResultSet=False, modifiedRowCount=None))
[2024-07-17T09:12:15.059+0000] {hive.py:609} DEBUG - TCloseOperationResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None))
[2024-07-17T09:12:15.059+0000] {hive.py:475} INFO - 
    CREATE TABLE IF NOT EXISTS my_table (
        id INT,
        name STRING
    )
    ROW FORMAT DELIMITED
    FIELDS TERMINATED BY ','
    STORED AS TEXTFILE;
    
[2024-07-17T09:12:15.059+0000] {hive.py:479} DEBUG - TExecuteStatementReq(sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=b'\xa0\xb0\xf2\x05s\xe4HN\xa4\xb0\xb2\xcc+G\xc3\x85', secret=b'\xbd\x99\xc1\r\xe9\xa2F\xcd\xa8\xa7h\xea\x14\xad\xc5e')), statement="\n    CREATE TABLE IF NOT EXISTS my_table (\n        id INT,\n        name STRING\n    )\n    ROW FORMAT DELIMITED\n    FIELDS TERMINATED BY ','\n    STORED AS TEXTFILE;\n    ", confOverlay=None, runAsync=False, queryTimeout=0)
[2024-07-17T09:12:15.063+0000] {hive.py:609} DEBUG - TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: ParseException line 8:22 extraneous input ';' expecting EOF near '<EOF>':17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.ParseException:line 8:22 extraneous input ';' expecting EOF near '<EOF>':22:6", 'org.apache.hadoop.hive.ql.parse.ParseDriver:parse:ParseDriver.java:219', 'org.apache.hadoop.hive.ql.parse.ParseUtils:parse:ParseUtils.java:77', 'org.apache.hadoop.hive.ql.parse.ParseUtils:parse:ParseUtils.java:70', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:468', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: ParseException line 8:22 extraneous input ';' expecting EOF near '<EOF>'"), operationHandle=None)
[2024-07-17T09:12:15.063+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 25, in create_hive_table
    cursor.execute('''
  File "/home/airflow/.local/lib/python3.10/site-packages/pyhive/hive.py", line 481, in execute
    _check_status(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/pyhive/hive.py", line 611, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: ParseException line 8:22 extraneous input ';' expecting EOF near '<EOF>':17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.ParseException:line 8:22 extraneous input ';' expecting EOF near '<EOF>':22:6", 'org.apache.hadoop.hive.ql.parse.ParseDriver:parse:ParseDriver.java:219', 'org.apache.hadoop.hive.ql.parse.ParseUtils:parse:ParseUtils.java:77', 'org.apache.hadoop.hive.ql.parse.ParseUtils:parse:ParseUtils.java:70', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:468', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: ParseException line 8:22 extraneous input ';' expecting EOF near '<EOF>'"), operationHandle=None)
[2024-07-17T09:12:15.070+0000] {taskinstance.py:527} DEBUG - Task Duration set to 0.253376
[2024-07-17T09:12:15.071+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T09:12:15.071+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=hive_etl, task_id=create_hive_table, execution_date=20240717T091032, start_date=20240717T091214, end_date=20240717T091215
[2024-07-17T09:12:15.079+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T09:12:15.079+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1616 for task create_hive_table (TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: ParseException line 8:22 extraneous input ';' expecting EOF near '<EOF>':17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.ParseException:line 8:22 extraneous input ';' expecting EOF near '<EOF>':22:6", 'org.apache.hadoop.hive.ql.parse.ParseDriver:parse:ParseDriver.java:219', 'org.apache.hadoop.hive.ql.parse.ParseUtils:parse:ParseUtils.java:77', 'org.apache.hadoop.hive.ql.parse.ParseUtils:parse:ParseUtils.java:70', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:468', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: ParseException line 8:22 extraneous input ';' expecting EOF near '<EOF>'"), operationHandle=None); 471)
[2024-07-17T09:12:15.093+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T09:12:15.141+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun hive_etl @ 2024-07-17 09:10:32.305646+00:00: manual__2024-07-17T09:10:32.305646+00:00, state:running, queued_at: 2024-07-17 09:10:32.314321+00:00. externally triggered: True>: 3 task(s)
[2024-07-17T09:12:15.142+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun hive_etl @ 2024-07-17 09:10:32.305646+00:00: manual__2024-07-17T09:10:32.305646+00:00, state:running, queued_at: 2024-07-17 09:10:32.314321+00:00. externally triggered: True>: 3 task(s)
[2024-07-17T09:12:15.142+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive manual__2024-07-17T09:10:32.305646+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:12:15.143+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive manual__2024-07-17T09:10:32.305646+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T09:12:15.143+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.load_data_into_hive manual__2024-07-17T09:10:32.305646+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T09:12:15.144+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive manual__2024-07-17T09:10:32.305646+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:12:15.144+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end manual__2024-07-17T09:10:32.305646+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:12:15.145+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end manual__2024-07-17T09:10:32.305646+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:12:15.145+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.end manual__2024-07-17T09:10:32.305646+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:12:15.146+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end manual__2024-07-17T09:10:32.305646+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:12:15.146+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-17T09:12:15.146750+00:00 and task will be retried at 2024-07-17T09:17:15.070166+00:00.
[2024-07-17T09:12:15.147+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-17T09:12:15.146750+00:00 and task will be retried at 2024-07-17T09:17:15.070166+00:00.
[2024-07-17T09:12:15.147+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [up_for_retry]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-17T09:12:15.148+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:10:32.305646+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:12:15.154+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
