[2024-07-17T09:44:21.069+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:44:21.112+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T09:44:21.128+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:44:21.134+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T09:44:21.163+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-04-18T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T09:44:21.172+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-04-18T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:44:21.173+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-04-18T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T09:44:21.173+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-04-18T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:44:21.173+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql scheduled__2023-04-18T00:00:00+00:00 [queued]>
[2024-07-17T09:44:21.180+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-04-18T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:44:21.187+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-04-18T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T09:44:21.189+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-04-18T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T09:44:21.191+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-04-18T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:44:21.192+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql scheduled__2023-04-18T00:00:00+00:00 [queued]>
[2024-07-17T09:44:21.193+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-17T09:44:21.226+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_from_mysql> on 2023-04-18 00:00:00+00:00
[2024-07-17T09:44:21.241+0000] {standard_task_runner.py:60} INFO - Started process 142 to run task
[2024-07-17T09:44:21.260+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hive_etl', 'extract_from_mysql', 'scheduled__2023-04-18T00:00:00+00:00', '--job-id', '1834', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmphxcvz3w8']
[2024-07-17T09:44:21.262+0000] {standard_task_runner.py:88} INFO - Job 1834: Subtask extract_from_mysql
[2024-07-17T09:44:21.263+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x7a4457f56f80>]
[2024-07-17T09:44:21.401+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:44:21.410+0000] {task_command.py:423} INFO - Running <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-04-18T00:00:00+00:00 [running]> on host d0d849f06491
[2024-07-17T09:44:21.411+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 142)
[2024-07-17T09:44:21.411+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 142)
[2024-07-17T09:44:21.412+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T09:44:21.497+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:44:21.503+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T09:44:21.513+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T09:44:21.552+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T09:44:21.577+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hive_etl' AIRFLOW_CTX_TASK_ID='extract_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2023-04-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-18T00:00:00+00:00'
[2024-07-17T09:44:21.578+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T09:44:21.578+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T09:44:21.609+0000] {base.py:83} INFO - Using connection ID 'mysql_default' for task execution.
[2024-07-17T09:44:21.636+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2024-07-17T09:44:21.646+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-17T09:44:21.648+0000] {__init__.py:73} DEBUG - Lineage called with inlets: [], outlets: []
[2024-07-17T09:44:21.667+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T09:44:21.667+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=hive_etl, task_id=extract_from_mysql, execution_date=20230418T000000, start_date=20240717T094421, end_date=20240717T094421
[2024-07-17T09:44:21.667+0000] {taskinstance.py:527} DEBUG - Task Duration set to 0.493598
[2024-07-17T09:44:21.688+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T09:44:21.711+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-17T09:44:21.797+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun hive_etl @ 2023-04-18 00:00:00+00:00: scheduled__2023-04-18T00:00:00+00:00, state:running, queued_at: 2024-07-17 09:44:18.556503+00:00. externally triggered: False>: 4 task(s)
[2024-07-17T09:44:21.798+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun hive_etl @ 2023-04-18 00:00:00+00:00: scheduled__2023-04-18T00:00:00+00:00, state:running, queued_at: 2024-07-17 09:44:18.556503+00:00. externally triggered: False>: 3 task(s)
[2024-07-17T09:44:21.799+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-18T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:44:21.799+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-18T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:44:21.800+0000] {taskinstance.py:1979} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: hive_etl.create_hive_table scheduled__2023-04-18T00:00:00+00:00 [None]>
[2024-07-17T09:44:21.801+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-18T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T09:44:21.802+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-18T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T09:44:21.803+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-18T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:44:21.803+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-18T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:44:21.804+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-04-18T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:44:21.805+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.end scheduled__2023-04-18T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:44:21.806+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-04-18T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:44:21.806+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-04-18T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:44:21.818+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
