[2024-07-17T09:49:40.193+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:49:40.210+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T09:49:40.225+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:49:40.228+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T09:49:40.252+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql manual__2024-07-17T09:47:58.834042+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T09:49:40.260+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql manual__2024-07-17T09:47:58.834042+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:49:40.261+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql manual__2024-07-17T09:47:58.834042+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T09:49:40.261+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql manual__2024-07-17T09:47:58.834042+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:49:40.261+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql manual__2024-07-17T09:47:58.834042+00:00 [queued]>
[2024-07-17T09:49:40.268+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql manual__2024-07-17T09:47:58.834042+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:49:40.273+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql manual__2024-07-17T09:47:58.834042+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T09:49:40.274+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql manual__2024-07-17T09:47:58.834042+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T09:49:40.274+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql manual__2024-07-17T09:47:58.834042+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:49:40.275+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql manual__2024-07-17T09:47:58.834042+00:00 [queued]>
[2024-07-17T09:49:40.275+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-17T09:49:40.293+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_from_mysql> on 2024-07-17 09:47:58.834042+00:00
[2024-07-17T09:49:40.303+0000] {standard_task_runner.py:60} INFO - Started process 362 to run task
[2024-07-17T09:49:40.308+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hive_etl', 'extract_from_mysql', 'manual__2024-07-17T09:47:58.834042+00:00', '--job-id', '1887', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmppe0r5df3']
[2024-07-17T09:49:40.310+0000] {standard_task_runner.py:88} INFO - Job 1887: Subtask extract_from_mysql
[2024-07-17T09:49:40.311+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x7a4457f56f80>]
[2024-07-17T09:49:40.372+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:49:40.378+0000] {task_command.py:423} INFO - Running <TaskInstance: hive_etl.extract_from_mysql manual__2024-07-17T09:47:58.834042+00:00 [running]> on host d0d849f06491
[2024-07-17T09:49:40.379+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 362)
[2024-07-17T09:49:40.380+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 362)
[2024-07-17T09:49:40.380+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T09:49:40.434+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:49:40.438+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T09:49:40.447+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T09:49:40.482+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T09:49:40.500+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hive_etl' AIRFLOW_CTX_TASK_ID='extract_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T09:47:58.834042+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T09:47:58.834042+00:00'
[2024-07-17T09:49:40.501+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T09:49:40.502+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T09:49:40.515+0000] {base.py:83} INFO - Using connection ID 'mysql_default' for task execution.
[2024-07-17T09:49:40.603+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2024-07-17T09:49:40.625+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-17T09:49:40.626+0000] {__init__.py:73} DEBUG - Lineage called with inlets: [], outlets: []
[2024-07-17T09:49:40.637+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T09:49:40.637+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=hive_etl, task_id=extract_from_mysql, execution_date=20240717T094758, start_date=20240717T094940, end_date=20240717T094940
[2024-07-17T09:49:40.637+0000] {taskinstance.py:527} DEBUG - Task Duration set to 0.375574
[2024-07-17T09:49:40.647+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T09:49:40.681+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-17T09:49:40.700+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun hive_etl @ 2024-07-17 09:47:58.834042+00:00: manual__2024-07-17T09:47:58.834042+00:00, state:running, queued_at: 2024-07-17 09:47:58.857748+00:00. externally triggered: True>: 4 task(s)
[2024-07-17T09:49:40.701+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun hive_etl @ 2024-07-17 09:47:58.834042+00:00: manual__2024-07-17T09:47:58.834042+00:00, state:running, queued_at: 2024-07-17 09:47:58.857748+00:00. externally triggered: True>: 3 task(s)
[2024-07-17T09:49:40.701+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:47:58.834042+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:49:40.702+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:47:58.834042+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:49:40.702+0000] {taskinstance.py:1979} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: hive_etl.create_hive_table manual__2024-07-17T09:47:58.834042+00:00 [None]>
[2024-07-17T09:49:40.703+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive manual__2024-07-17T09:47:58.834042+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T09:49:40.703+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.load_data_into_hive manual__2024-07-17T09:47:58.834042+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T09:49:40.703+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive manual__2024-07-17T09:47:58.834042+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:49:40.703+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive manual__2024-07-17T09:47:58.834042+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:49:40.704+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end manual__2024-07-17T09:47:58.834042+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:49:40.704+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.end manual__2024-07-17T09:47:58.834042+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:49:40.705+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end manual__2024-07-17T09:47:58.834042+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:49:40.705+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end manual__2024-07-17T09:47:58.834042+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:49:40.714+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
