[2024-07-17T04:28:04.209+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T04:28:04.218+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T04:28:04.227+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T04:28:04.229+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T04:28:04.246+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.extract_from_mysql manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-17T04:28:04.250+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.extract_from_mysql manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T04:28:04.251+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.extract_from_mysql manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T04:28:04.251+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.extract_from_mysql manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T04:28:04.251+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.extract_from_mysql manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T04:28:04.251+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_hive_with_connection.extract_from_mysql manual__2024-07-17T04:28:02.397521+00:00 [queued]>
[2024-07-17T04:28:04.253+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.extract_from_mysql manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T04:28:04.256+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.extract_from_mysql manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T04:28:04.256+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.extract_from_mysql manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T04:28:04.256+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.extract_from_mysql manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T04:28:04.256+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.extract_from_mysql manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-17T04:28:04.257+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_hive_with_connection.extract_from_mysql manual__2024-07-17T04:28:02.397521+00:00 [queued]>
[2024-07-17T04:28:04.258+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-17T04:28:04.267+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_from_mysql> on 2024-07-17 04:28:02.397521+00:00
[2024-07-17T04:28:04.272+0000] {standard_task_runner.py:60} INFO - Started process 402 to run task
[2024-07-17T04:28:04.274+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_hive_with_connection', 'extract_from_mysql', 'manual__2024-07-17T04:28:02.397521+00:00', '--job-id', '1395', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmpz6_h1wg8']
[2024-07-17T04:28:04.275+0000] {standard_task_runner.py:88} INFO - Job 1395: Subtask extract_from_mysql
[2024-07-17T04:28:04.276+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x70bb58c4af80>]
[2024-07-17T04:28:04.307+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T04:28:04.310+0000] {task_command.py:423} INFO - Running <TaskInstance: mysql_to_hive_with_connection.extract_from_mysql manual__2024-07-17T04:28:02.397521+00:00 [running]> on host b2f9507f2158
[2024-07-17T04:28:04.310+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 402)
[2024-07-17T04:28:04.310+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 402)
[2024-07-17T04:28:04.310+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T04:28:04.335+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T04:28:04.336+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T04:28:04.339+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T04:28:04.357+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T04:28:04.367+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_hive_with_connection' AIRFLOW_CTX_TASK_ID='extract_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T04:28:02.397521+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T04:28:02.397521+00:00'
[2024-07-17T04:28:04.367+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T04:28:04.368+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T04:28:04.376+0000] {base.py:83} INFO - Using connection ID 'mysql_default' for task execution.
[2024-07-17T04:28:04.441+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2024-07-17T04:28:04.469+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-17T04:28:04.470+0000] {__init__.py:73} DEBUG - Lineage called with inlets: [], outlets: []
[2024-07-17T04:28:04.478+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T04:28:04.478+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=mysql_to_hive_with_connection, task_id=extract_from_mysql, execution_date=20240717T042802, start_date=20240717T042804, end_date=20240717T042804
[2024-07-17T04:28:04.478+0000] {taskinstance.py:527} DEBUG - Task Duration set to 0.226679
[2024-07-17T04:28:04.485+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T04:28:04.526+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-17T04:28:04.540+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun mysql_to_hive_with_connection @ 2024-07-17 04:28:02.397521+00:00: manual__2024-07-17T04:28:02.397521+00:00, state:running, queued_at: 2024-07-17 04:28:02.403947+00:00. externally triggered: True>: 2 task(s)
[2024-07-17T04:28:04.540+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun mysql_to_hive_with_connection @ 2024-07-17 04:28:02.397521+00:00: manual__2024-07-17T04:28:02.397521+00:00, state:running, queued_at: 2024-07-17 04:28:02.403947+00:00. externally triggered: True>: 1 task(s)
[2024-07-17T04:28:04.540+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T04:28:04.541+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T04:28:04.541+0000] {taskinstance.py:1979} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [None]>
[2024-07-17T04:28:04.543+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
