[2024-07-17T14:25:28.838+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:25:28.853+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T14:25:28.869+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:25:28.873+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T14:25:28.902+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T14:25:28.902+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:25:28.912+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:25:28.913+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T14:25:28.913+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2024-07-17T14:25:28.914+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:25:28.917+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:25:28.926+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T14:25:28.926+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T14:25:28.927+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2024-07-17T14:25:28.927+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-17T14:25:28.945+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_from_mysql> on 2023-07-01 00:00:00+00:00
[2024-07-17T14:25:28.955+0000] {standard_task_runner.py:60} INFO - Started process 367 to run task
[2024-07-17T14:25:28.958+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hive_etl', 'extract_from_mysql', 'scheduled__2023-07-01T00:00:00+00:00', '--job-id', '2158', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmpwrq38_e6']
[2024-07-17T14:25:28.960+0000] {standard_task_runner.py:88} INFO - Job 2158: Subtask extract_from_mysql
[2024-07-17T14:25:28.960+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x763f8104af80>]
[2024-07-17T14:25:29.012+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:25:29.016+0000] {task_command.py:423} INFO - Running <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [running]> on host 8c50a8ad787d
[2024-07-17T14:25:29.017+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 367)
[2024-07-17T14:25:29.018+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 367)
[2024-07-17T14:25:29.018+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T14:25:29.071+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:25:29.075+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T14:25:29.081+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T14:25:29.114+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T14:25:29.135+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hive_etl' AIRFLOW_CTX_TASK_ID='extract_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2023-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-01T00:00:00+00:00'
[2024-07-17T14:25:29.136+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T14:25:29.137+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T14:25:29.156+0000] {base.py:83} INFO - Using connection ID 'mysql_default' for task execution.
[2024-07-17T14:25:34.006+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:25:39.047+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:25:44.084+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:25:49.137+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:25:54.211+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:25:59.250+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:26:04.288+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:26:09.326+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:26:14.365+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:26:19.402+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:26:24.442+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:26:29.483+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:26:34.537+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:26:39.581+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:26:44.619+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:26:49.699+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:26:54.746+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:26:59.784+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:27:04.852+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:27:09.891+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:27:14.942+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:27:19.980+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:27:25.021+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:27:30.090+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:27:35.132+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:27:40.170+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:27:43.918+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 20, in extract_from_mysql
    df = mysql_hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 226, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 195, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on '172.16.9.72' (115)")
[2024-07-17T14:27:43.926+0000] {taskinstance.py:527} DEBUG - Task Duration set to 135.012585
[2024-07-17T14:27:43.929+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T14:27:43.929+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=hive_etl, task_id=extract_from_mysql, execution_date=20230701T000000, start_date=20240717T142528, end_date=20240717T142743
[2024-07-17T14:27:43.943+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T14:27:43.943+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2158 for task extract_from_mysql ((2002, "Can't connect to server on '172.16.9.72' (115)"); 367)
[2024-07-17T14:27:43.990+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T14:27:44.174+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun hive_etl @ 2023-07-01 00:00:00+00:00: scheduled__2023-07-01T00:00:00+00:00, state:running, queued_at: 2024-07-17 14:25:26.824101+00:00. externally triggered: False>: 4 task(s)
[2024-07-17T14:27:44.175+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun hive_etl @ 2023-07-01 00:00:00+00:00: scheduled__2023-07-01T00:00:00+00:00, state:running, queued_at: 2024-07-17 14:25:26.824101+00:00. externally triggered: False>: 4 task(s)
[2024-07-17T14:27:44.175+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-07-01T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:27:44.175+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-07-01T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'extract_from_mysql'}
[2024-07-17T14:27:44.176+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.create_hive_table scheduled__2023-07-01T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'extract_from_mysql'}
[2024-07-17T14:27:44.176+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-07-01T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:27:44.176+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-07-01T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:27:44.177+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-07-01T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T14:27:44.177+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-07-01T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T14:27:44.177+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-07-01T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:27:44.178+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-07-01T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:27:44.178+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-07-01T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T14:27:44.178+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.end scheduled__2023-07-01T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T14:27:44.178+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-07-01T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:27:44.179+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:27:44.179+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [up_for_retry]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-17T14:27:44.179+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-17T14:27:44.179776+00:00 and task will be retried at 2024-07-17T14:32:43.926824+00:00.
[2024-07-17T14:27:44.180+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-01T00:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-17T14:27:44.179776+00:00 and task will be retried at 2024-07-17T14:32:43.926824+00:00.
[2024-07-17T14:27:44.188+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
