[2024-07-17T14:15:00.644+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:15:00.653+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T14:15:00.661+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:15:00.663+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T14:15:00.678+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T14:15:00.678+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:15:00.682+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:15:00.683+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T14:15:00.683+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2024-07-17T14:15:00.683+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:15:00.684+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:15:00.689+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T14:15:00.689+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T14:15:00.689+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2024-07-17T14:15:00.689+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-17T14:15:00.698+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_from_mysql> on 2023-06-08 00:00:00+00:00
[2024-07-17T14:15:00.701+0000] {standard_task_runner.py:60} INFO - Started process 104 to run task
[2024-07-17T14:15:00.703+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hive_etl', 'extract_from_mysql', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '2119', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmp2yyg_ua8']
[2024-07-17T14:15:00.704+0000] {standard_task_runner.py:88} INFO - Job 2119: Subtask extract_from_mysql
[2024-07-17T14:15:00.705+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x763f8104af80>]
[2024-07-17T14:15:00.733+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:15:00.735+0000] {task_command.py:423} INFO - Running <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [running]> on host 8c50a8ad787d
[2024-07-17T14:15:00.735+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 104)
[2024-07-17T14:15:00.735+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 104)
[2024-07-17T14:15:00.735+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T14:15:00.757+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:15:00.758+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T14:15:00.762+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T14:15:00.778+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T14:15:00.791+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hive_etl' AIRFLOW_CTX_TASK_ID='extract_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2023-06-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-08T00:00:00+00:00'
[2024-07-17T14:15:00.792+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T14:15:00.792+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T14:15:00.798+0000] {base.py:83} INFO - Using connection ID 'mysql_default' for task execution.
[2024-07-17T14:15:05.746+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:15:10.796+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:15:15.847+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:15:20.888+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:15:25.929+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:15:30.978+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:15:36.020+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:15:41.100+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:15:46.163+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:15:51.219+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:15:56.257+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:16:01.298+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:16:06.367+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:16:11.408+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:16:16.446+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:16:21.495+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:16:26.535+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:16:31.575+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:16:36.627+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:16:41.680+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:16:46.731+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:16:51.774+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:16:56.816+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:17:01.855+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:17:06.908+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:17:11.960+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:17:15.185+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 20, in extract_from_mysql
    df = mysql_hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 226, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 195, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on '172.16.9.72' (115)")
[2024-07-17T14:17:15.194+0000] {taskinstance.py:527} DEBUG - Task Duration set to 134.511287
[2024-07-17T14:17:15.196+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T14:17:15.196+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=hive_etl, task_id=extract_from_mysql, execution_date=20230608T000000, start_date=20240717T141500, end_date=20240717T141715
[2024-07-17T14:17:15.301+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T14:17:15.302+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2119 for task extract_from_mysql ((2002, "Can't connect to server on '172.16.9.72' (115)"); 104)
[2024-07-17T14:17:15.341+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T14:17:15.354+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun hive_etl @ 2023-06-08 00:00:00+00:00: scheduled__2023-06-08T00:00:00+00:00, state:running, queued_at: 2024-07-17 14:14:58.487287+00:00. externally triggered: False>: 4 task(s)
[2024-07-17T14:17:15.354+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun hive_etl @ 2023-06-08 00:00:00+00:00: scheduled__2023-06-08T00:00:00+00:00, state:running, queued_at: 2024-07-17 14:14:58.487287+00:00. externally triggered: False>: 4 task(s)
[2024-07-17T14:17:15.354+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-06-08T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:17:15.355+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-06-08T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'extract_from_mysql'}
[2024-07-17T14:17:15.355+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.create_hive_table scheduled__2023-06-08T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'extract_from_mysql'}
[2024-07-17T14:17:15.355+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-06-08T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:17:15.355+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-06-08T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:17:15.355+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-06-08T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T14:17:15.356+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-06-08T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T14:17:15.356+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-06-08T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:17:15.356+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-06-08T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:17:15.356+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-06-08T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T14:17:15.356+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.end scheduled__2023-06-08T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T14:17:15.356+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-06-08T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:17:15.357+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:17:15.357+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [up_for_retry]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-17T14:17:15.357+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-17T14:17:15.357362+00:00 and task will be retried at 2024-07-17T14:22:15.194709+00:00.
[2024-07-17T14:17:15.357+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-08T00:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-17T14:17:15.357362+00:00 and task will be retried at 2024-07-17T14:22:15.194709+00:00.
[2024-07-17T14:17:15.361+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
